"""create wohnungen table

Revision ID: ce15e2b24646
Revises: 
Create Date: 2026-07-13 11:01:46.736353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce15e2b24646'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wohnungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genossenschaft', sa.String(), nullable=False),
    sa.Column('quelle_url', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('viertel', sa.String(), nullable=True),
    sa.Column('zimmer', sa.Float(), nullable=True),
    sa.Column('preis', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('bild_urls', sa.JSON(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quelle_url', name='uq_wohnungen_quelle_url')
    )
    op.create_index(op.f('ix_wohnungen_genossenschaft'), 'wohnungen', ['genossenschaft'], unique=False)
    op.create_index(op.f('ix_wohnungen_quelle_url'), 'wohnungen', ['quelle_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wohnungen_quelle_url'), table_name='wohnungen')
    op.drop_index(op.f('ix_wohnungen_genossenschaft'), table_name='wohnungen')
    op.drop_table('wohnungen')
    # ### end Alembic commands ###
